### PR TITLE
Fall back to read() method if read1() attribute is not available

### PR DESCRIPTION
**Pull request by Kami**
This pull request fixes regression introduced in #21 (8585bac65841c0ba9f6b79d59eb77c438abac86d).

After upgrading to the latest version our code started failing with the following error:

```bash
'_fileobject' object has no attribute 'read1'
```

This seems to consistently happen under Python 2.7.x using sseclient 0.0.23.

### CODE REVIEW

**Comment by Kami** [comment]
@mutantmonkey Just curious, under which Python (and requests) version did you test your change?

**Comment by mutantmonkey** [comment]
@Kami I tested (and I'm currently running in production) with Python 3.7 and requests 2.21.0.

I've already opened #25 to fix this issue.

**Comment by btubbs** [comment]
@Kami and @mutantmonkey I just realized you two submitted dueling PRs with the same fix.  I merged @mutantmonkey's before I realized that.  It looks like the two changes aren't quite the same though.  Which one is more correct?

**Comment by Kami** [comment]
@btubbs #25 should work fine (and it's slightly safer). I will close this one.

Thanks.
